:toc: macro
:toclevels: 5
:figure-caption!:

= Docker Alpine Ruby

Provides a Ruby focused Docker image with current tooling for development purposes. Great for
local development and/or continuous integration builds using the most up-to-date tooling.

toc::[]

== Features

* Uses the link:https://alchemists.io/projects/docker-alpine-base[Docker Alpine Base] image.
* Installs link:https://www.ruby-lang.org[Ruby] with link:https://speed.yjit.org[YJIT].
* Updates link:https://rubygems.org[RubyGems].

== Requirements

. link:https://www.docker.com[Docker].

== Setup

To set up the project, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/docker-alpine-ruby.git
cd docker-alpine-ruby
git checkout 3.6.0
----

== Usage

All versions of this image can be found on
link:https://hub.docker.com/repository/docker/bkuhlmann/alpine-ruby[Docker Hub]. The image can be
pulled as follows:

[source,bash]
----
docker pull bkuhlmann/alpine-ruby:latest  # <= Pull latest version.
docker pull bkuhlmann/alpine-ruby:3.6.0   # <= Pull specific version.
----

You can also build on top of this image via your `Dockerfile`:

[source,dockerfile]
----
FROM bkuhlmann/alpine-ruby:latest  # <= Latest version.
FROM bkuhlmann/alpine-ruby:3.6.0   # <= Specific version.
----

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/docker-alpine-ruby.git
cd docker-alpine-ruby
----

To build, run:

[source,bash]
----
bin/build
----

To use the console, run:

[source,bash]
----
bin/console
----

To deploy a new version (i.e. `1.2.3`), run:

[source,bash]
----
bin/deploy 1.2.3
----

Deploying, without specifying a version, will default to tagging the image as `latest`. Best practice is to deploy both the latest version and specific tag. Example:

[source,bash]
----
bin/deploy
bin/deploy 1.2.3
----

== Tests

To test, run:

[source,bash]
----
bin/console
ruby --version
----

== link:https://alchemists.io/policies/license[License]

== link:https://alchemists.io/policies/security[Security]

== link:https://alchemists.io/policies/code_of_conduct[Code of Conduct]

== link:https://alchemists.io/policies/contributions[Contributions]

== link:https://alchemists.io/projects/docker-alpine-ruby/versions[Versions]

== link:https://alchemists.io/community[Community]

== Credits

* Built with link:https://alchemists.io/projects/rubysmith[Rubysmith].
* Engineered by link:https://alchemists.io/team/brooke_kuhlmann[Brooke Kuhlmann].
